#pragma once


#define I_NODE_SIZE 8
#define BLOCK_SIZE 32

#define I_NODE_COUNT 256
#define BLOCK_COUNT 256

#define I_NODE_BITMAP_SIZE (I_NODE_COUNT / 8)
#define BLOCK_BITMAP_SIZE (BLOCK_COUNT / 8)

#define SUPERBLOCK_SIZE 40

#define SUPERBLOCK_DATA_OFFSET 0
#define I_NODE_BITMAP_DATA_OFFSET (SUPERBLOCK_DATA_OFFSET + SUPERBLOCK_SIZE)
#define BLOCK_BITMAP_DATA_OFFSET (I_NODE_BITMAP_DATA_OFFSET + I_NODE_BITMAP_SIZE)
#define I_NODE_DATA_OFFSET (BLOCK_BITMAP_DATA_OFFSET + BLOCK_BITMAP_SIZE)
#define BLOCK_DATA_OFFSET (I_NODE_DATA_OFFSET + I_NODE_COUNT * I_NODE_SIZE)
#define END_OFFSET (BLOCK_DATA_OFFSET + BLOCK_COUNT * BLOCK_SIZE)