#pragma once


#define MINIFS__I_NODE_SIZE 8
#define MINIFS__BLOCK_SIZE 32

#define MINIFS__I_NODE_COUNT 256
#define MINIFS__BLOCK_COUNT 256

#define MINIFS__I_NODE_BITMAP_SIZE (MINIFS__I_NODE_COUNT / 8)
#define MINIFS__BLOCK_BITMAP_SIZE (MINIFS__BLOCK_COUNT / 8)

#define MINIFS__SUPERBLOCK_SIZE 40

#define MINIFS__SUPERBLOCK_DATA_OFFSET 0
#define MINIFS__I_NODE_BITMAP_DATA_OFFSET (MINIFS__SUPERBLOCK_DATA_OFFSET + MINIFS__SUPERBLOCK_SIZE)
#define MINIFS__BLOCK_BITMAP_DATA_OFFSET (MINIFS__I_NODE_BITMAP_DATA_OFFSET + MINIFS__I_NODE_BITMAP_SIZE)
#define MINIFS__I_NODE_DATA_OFFSET (MINIFS__BLOCK_BITMAP_DATA_OFFSET + MINIFS__BLOCK_BITMAP_SIZE)
#define MINIFS__BLOCK_DATA_OFFSET (MINIFS__I_NODE_DATA_OFFSET + MINIFS__I_NODE_COUNT * MINIFS__I_NODE_SIZE)
#define MINIFS__END_OFFSET (MINIFS__BLOCK_DATA_OFFSET + MINIFS__BLOCK_COUNT * MINIFS__BLOCK_SIZE)